-- GURU v1.2.0 workspace cloud-save table
-- Run this in Supabase SQL Editor if cloud save shows table/RLS error.

create table if not exists public.guru_workspaces (
  project_id text primary key,
  project_name text,
  workspace_data jsonb not null default '{}'::jsonb,
  schema_version text,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.guru_workspace_versions (
  id bigint generated by default as identity primary key,
  project_id text not null,
  workspace_data jsonb not null,
  source_updated_at timestamptz,
  saved_at timestamptz not null default now()
);

create index if not exists guru_workspace_versions_project_saved_idx
  on public.guru_workspace_versions (project_id, saved_at desc);

alter table public.guru_workspaces enable row level security;
alter table public.guru_workspace_versions enable row level security;

-- Синхронизация идёт только через серверные /api-функции с service_role.
-- Публичному anon/publishable ключу доступ к рабочим данным не выдаётся.
drop policy if exists "guru_workspaces_select_mvp" on public.guru_workspaces;
drop policy if exists "guru_workspaces_insert_mvp" on public.guru_workspaces;
drop policy if exists "guru_workspaces_update_mvp" on public.guru_workspaces;
drop policy if exists "guru_workspaces_delete_mvp" on public.guru_workspaces;

drop policy if exists "guru_workspace_versions_select_mvp" on public.guru_workspace_versions;
drop policy if exists "guru_workspace_versions_insert_mvp" on public.guru_workspace_versions;
